### ISSUE TITLE
xcode9 update_xcode_plugins show Gem::GemNotFoundException

### ISSUE THREAD

**Issue by Ambtion** [inket/update_xcode_plugins#41]
```
 ~ update_xcode_plugins 
/Users/***/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems.rb:270:in `find_spec_for_exe': can't find gem update_xcode_plugins (>= 0.a) (Gem::GemNotFoundException)
	from /Users/***/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems.rb:298:in `activate_bin_path'
	from /Users/***/.rvm/rubies/ruby-2.2.2/bin/update_xcode_plugins:22:in `<main>'
	from /Users/***/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/***/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'``
```

**Comment by inket** [comment]
Try one of the suggestions under **Install**: https://github.com/inket/update_xcode_plugins#install
